### ISSUE TITLE
Tabs with playing audio / speaker icon

### ISSUE THREAD

**Issue by kinsi55** [pellaeon/firefox-91plus-photon-userchrome#3]
Its beyond me why they would make it so the icon of the website is replaced with a speaker instead of having it seperated like before - I can never find the tab that I'm looking for because its missing the icon, can that be reverted?

**Comment by pellaeon** [comment]
Thanks for reporting, I will fix this.

**Comment by pellaeon** [comment]
Fixed in ab2e27b
