### ISSUE TITLE
2 loading bars when loading page

### ISSUE THREAD

**Issue by dvoraking** [pellaeon/firefox-91plus-photon-userchrome#9]
https://imgur.com/a/UVyrMUh

Great work you've done here. Sorry if this has been mentioned already. There's a bar at the top and one in the middle to indicate loading. I've been stuck in Proton limbo so long, I can't tell which is the old one. But I think the top one bouncing about is more annoying than the subtle one next to the page title. Having them both there is infuriating, though.

**Comment by pellaeon** [comment]
You can disable the top bouncing line by removing the line `@import "tab_line_loading_indicator.css";`
